NAME = ft_display_file
SRCS = ft_display_file.c
OBJ = ft_display_file.o
FLAGS = -Wall -Wextra -Werror -o

all: $(NAME)

$(NAME):
		gcc $(FLAGS) $(NAME) $(SRCS)

clean:
	/bin/rm -f $(OBJ)

fclean:	clean
	/bin/rm -f $(NAME)

re:	fclean all
